server:
  port: 8083
spring:
  application:
    name: business-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
seata:
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}_tx_group
  config:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      data-id: seataServer.properties
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      cluster: default
logging:
  level:
    org:
      reflections:
        Reflections: warn
    com:
      alibaba:
        nacos:
          common:
            remote:
              client: warn

